### PR TITLE
Update documentation to include osSensor version requirement

### PR DESCRIPTION
**Pull request by mstratford-dt**
*Issue #, if available:*

N/A

*Description of changes:*

- Adds osSensor version 6.0 note for traffic mirroring.
- Updates a generated text that was not previously updated.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tbulding** [comment]
Local testing successful

**Review by davmayd — APPROVED** [review]

**Pull request merged**
